spring:


  application:
    name: proyect-yml
server:
    port: 8081

    mongodb:
      host: localhost
      port: 27017
      database: ejemplo01
      # username: myusername
      # password: mypassword
      data:
        mongodb:
          auto-index-creation: true

